OJ-1369 manually bootstrap api with o auth into dev account
alphagov/di-ipv-cri-toy-api pull request #1
Opened 2023-05-02 08:00 UTC by scronk1

First pass of oauth and APIs

2023-05-02 11:19 UTC, jkunle commented on infrastructure/private-api.yaml
> +                    type: "string"
I think we can remove these

2023-05-02 16:37 UTC, jkunle approved these changes

2023-05-03 16:12 UTC, merlinc requested changes
Sorry, I'm gonna be a jerk and block this until my bootstrap PR is merged as it's likely to cause conflicts with what you've got here, and I think it will be useful to demo how to get around them

(apart from that it looks good to me! :smile:  )

2023-05-04 08:37 UTC, scronk1 commented
> Sorry, I'm gonna be a jerk and block this until my bootstrap PR is merged as it's likely to cause conflicts with what you've got here, and I think it will be useful to demo how to get around them
> 
> (apart from that it looks good to me! 😄 )

No dramas 😄

2023-05-04 15:39 UTC, scronk1 commented
Covered by different PR

2023-05-04 15:39 UTC, closed without merging