Added imposter yaml
alphagov/di-ipv-cri-toy-api pull request #7
Opened 2023-05-15 15:09 UTC by surajkumar

## Proposed changes

### What changed
Added `public-api-config.yaml` and `private-api-config.yaml`

### Why did it change

So we can run tests using imposter.

### Issue tracking

- [OJ-1398](https://govukverify.atlassian.net/browse/OJ-1398)

## Checklists

### Environment variables or secrets

- [X] No environment variables or secrets were added or changed

2023-05-15 15:52 UTC, scronk1 requested changes
The API paths are all good 👍  Just some imposter config issues

2023-05-15 15:52 UTC, scronk1 commented on infrastructure/private-api-config.yaml
> +      SessionHeader: session-id
`SessionHeader` is just the term we're using to reference in that spec - it's not something that actually goes into the query. To achieve this we need to do:
```
requestHeaders:
    session-id: <whatever you want to match on>
```

2023-05-15 15:52 UTC, scronk1 commented on infrastructure/private-api-config.yaml
> +      statusCode: 400
What use case are you hoping to achieve here? They have a session-id header but it's blank / the wrong thing?

2023-05-15 15:52 UTC, scronk1 commented on infrastructure/private-api-config.yaml
> +    requestHeaders:
This doesn't need `requestHeaders` - if we want this to be the default behaviour if the 200 and 400 criteria aren't matched then you can just keep it super simple

2023-05-15 15:52 UTC, scronk1 commented on infrastructure/private-api-config.yaml
> +      value: ipv-core-stub
Can this be `ipv-toy-stub` or something - core stub is a term used for a different stub so we don't want confusion

2023-05-15 15:52 UTC, scronk1 commented on infrastructure/private-api-config.yaml
> +      value: invalid
How are you triggering this in a request? I'm trying multiple things and just getting 400

2023-05-15 15:52 UTC, scronk1 commented on infrastructure/private-api-config.yaml
> +      SessionHeader: session-id
same as above - `SessionHeader` not necessary

2023-05-15 15:52 UTC, scronk1 commented on infrastructure/private-api-config.yaml
> +      value: football
Can these examples match the third party stub spec we've got for the toy api - https://github.com/alphagov/di-ipv-third-party-stubs/blob/main/stubs/toy/api-config.yaml

2023-05-15 15:52 UTC, scronk1 commented on infrastructure/public-api-config.yaml
> +      code: aaaaaaaaa
I love the energy but can we have something a bit more relevant?

2023-05-15 15:52 UTC, scronk1 commented on infrastructure/public-api-config.yaml
> +      SessionHeader: Authorization Bearer 123456789
Same as above - this should be session-id not SessionHeader
Also I think you've got a duplicate with the block above, shouldn't have more than one 200 response

2023-05-15 16:03 UTC, surajkumar commented on infrastructure/private-api-config.yaml
> +      value: invalid
setting the value to invalid in the body? I can refactor this for easier usage.

2023-05-18 07:11 UTC, surajkumar commented
Closing this PR in favour for the new branch I created

2023-05-18 07:11 UTC, closed without merging